export const DEFAULT_TEXTS = {
  GASTRO: {
    heroHeadline: "Découvrez l'excellence culinaire",
    heroSubtitle: "Une cuisine raffinée pour les moments les plus précieux",
    aboutTitle: "Notre savoir-faire",
    aboutParagraph1: "Depuis [X] années, notre chef sélectionne les meilleurs produits du terroir pour créer des plats qui racontent une histoire.",
    aboutParagraph2: "Chaque service est une expérience, où le goût, l'élégance et le partage se rencontrent.",
    specialtyName: "Signature du Chef",
    specialtyDescription: "Notre plat signature, sublimé par des produits locaux et une touche de créativité.",
    ctaPrimary: "Réserver",
    ctaSecondary: "Découvrir le menu",
  },
  BRASSERIE: {
    heroHeadline: "Saveurs authentiques et chaleureuses",
    heroSubtitle: "L'esprit bistrot, la cuisine traditionnelle française",
    aboutTitle: "La tradition française",
    aboutParagraph1: "Notre brasserie perpétue l'art de vivre français, avec des plats réconfortants et une ambiance conviviale.",
    aboutParagraph2: "Ici, on prend le temps de savourer chaque bouchée, dans une déco authentique et chaleureuse.",
    specialtyName: "Plat du Jour",
    specialtyDescription: "Notre plat du jour, préparé avec amour chaque matin selon les produits disponibles sur les marchés.",
    ctaPrimary: "S'asseoir",
    ctaSecondary: "Voir la carte",
  },
  BAR: {
    heroHeadline: "Cocktails & Ambiance",
    heroSubtitle: "L'art du cocktail et des soirées mémorables",
    aboutTitle: "Notre Bar",
    aboutParagraph1: "Notre bar mixe tradition et créativité pour créer des cocktails uniques et mémorables.",
    aboutParagraph2: "Que vous soyez amateur de classiques ou à la recherche d'une découverte, notre barman vous propose une expérience sur-mesure.",
    specialtyName: "Cocktail Signature",
    specialtyDescription: "Notre cocktail signature, revisité avec des ingrédients premium et une touche d'originalité.",
    ctaPrimary: "Boire un verre",
    ctaSecondary: "Voir la carte",
  },
  CAFE: {
    heroHeadline: "Le café dans tous ses états",
    heroSubtitle: "Grains sélectionnés, torréfaction artisanale, barista passionné",
    aboutTitle: "Notre Passion du Café",
    aboutParagraph1: "Nous sélectionnons les meilleurs grains arabica et robusta, torréfiés artisanalement dans notre atelier.",
    aboutParagraph2: "Chaque espresso est préparé avec soin pour extraire le meilleur de chaque grain, pour vous offrir un café d'exception.",
    specialtyName: "Spécialité du Moment",
    specialtyDescription: "Nos spécialités du moment, préparées avec les mêmes exigences de qualité que nos cafés.",
    ctaPrimary: "Prendre un café",
    ctaSecondary: "Voir la carte",
  },
  PIZZERIA: {
    heroHeadline: "Pizza authentique napolitaine",
    heroSubtitle: "Pâte faite maison, four à bois, ingrédients frais",
    aboutTitle: "Notre Tradition Pizza",
    aboutParagraph1: "Notre pâte est préparée chaque jour avec de la farine italienne de qualité supérieure et laisse reposer 48h.",
    aboutParagraph2: "Nos ingrédients sont sélectionnés pour leur authenticité : mozzarella di bufala, tomates San Marzano, basilic frais.",
    specialtyName: "Pizza Signature",
    specialtyDescription: "Notre pizza signature, parfaite pour partager : couche généreuse de fromage, basilic frais, et huile d'olive extra vierge.",
    ctaPrimary: "Commander",
    ctaSecondary: "Voir le menu",
  },
  FAST_FOOD: {
    heroHeadline: "Burger & Plus",
    heroSubtitle: "Ingrédients frais, recettes maison, rapidité",
    aboutTitle: "Notre Concept",
    aboutParagraph1: "Nous préparons chaque burger à la commande avec des ingrédients frais et locaux quand c'est possible.",
    aboutParagraph2: "Nos sauces sont maison, nos frites cuites à la commande, pour vous offrir une qualité optimale.",
    specialtyName: "Signature Burger",
    specialtyDescription: "Notre burger signature : bœuf charolais, cheddar affiné, sauce secrète maison, bun brioche.",
    ctaPrimary: "Commander",
    ctaSecondary: "Voir la carte",
  },
  OTHER: {
    heroHeadline: "Bienvenue chez [Nom]",
    heroSubtitle: "Cuisine authentique, produits frais, ambiance conviviale",
    aboutTitle: "À Propos",
    aboutParagraph1: "[Nom] est un restaurant passionné par la cuisine authentique et les produits frais du terroir.",
    aboutParagraph2: "Nous préparons chaque plat avec amour pour vous offrir une expérience mémorable.",
    specialtyName: "Notre Spécialité",
    specialtyDescription: "Notre plat signature, préparé avec des ingrédients locaux et une touche de créativité.",
    ctaPrimary: "Découvrir",
    ctaSecondary: "Voir le menu",
  },
} as const;

export type RestaurantType = keyof typeof DEFAULT_TEXTS;
